# Generated by Django 4.0.6 on 2022-07-29 19:49

from django.db import migrations
from apps.blog.models import BlogCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Новости',
        'Обзоры',
        'Акции',
        'Партнерам',
        'Специальные предложения',
    ]
    for category in categories:
        BlogCategory.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_tag_options_alter_article_tags_alter_tag_name'),
    ]

    operations = [
        # migrations.RunPython(add_blog_categories)
    ]