# Generated by Django 4.0.6 on 2022-08-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Единицу товара', 'verbose_name_plural': 'Товар'},
        ),
    ]
