# Generated by Django 4.0.6 on 2022-08-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tree_id',
        ),
    ]
