# Generated by Django 4.0.6 on 2022-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_level_remove_product_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantiti',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
