# Generated by Django 4.0.6 on 2022-08-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
