# Generated by Django 4.0.6 on 2022-09-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='О себе'),
        ),
    ]
